baseURL = 'http://ojf-electrical.co.uk'
title = 'Trusted and professional electrical services in Lincolnshire'

languageCode = 'en-us'
uglyurls = true
canonifyURLs = false
relativeURLs = true
disableKinds = ['taxonomy', 'term', 'RSS']
sectionPagesMenu = ['main', 'footer']

[markup.goldmark.parser]
    autoHeadingID = false
    
[markup.goldmark.renderer]
    unsafe = true
    hardWraps = true