baseURL = 'http://localhost'
title = 'Trusted and professional #industry services in #towncity'

languageCode = 'en-us'
uglyurls = true
canonifyURLs = false
relativeURLs = true
disableKinds = ['taxonomy', 'term', 'RSS']
sectionPagesMenu = ['main', 'footer']

[markup.goldmark.parser]
    autoHeadingID = false
    
[markup.goldmark.renderer]
    unsafe = true
    hardWraps = true