baseURL = 'http://www.youvebeenrecovered.co.uk'
title = 'Trusted and professional vehicle recovery services in Glasgow'

languageCode = 'en-us'
uglyurls = true
canonifyURLs = false
relativeURLs = true
disableKinds = ['taxonomy', 'term', 'RSS']
sectionPagesMenu = ['main', 'footer']

[markup.goldmark.parser]
    autoHeadingID = false
    
[markup.goldmark.renderer]
    unsafe = true
    hardWraps = true

[module]
    [[module.mounts]]
        source = "assets/images"
        target = "static/images"