baseURL = 'http://vale-electrical.uk'
title = ''

languageCode = 'en-us'
uglyurls = true
canonifyURLs = false
relativeURLs = true
disableKinds = ['taxonomy', 'term', 'RSS']
sectionPagesMenu = ['main', 'footer', 'services',]

[markup.goldmark.parser]
    autoHeadingID = false
    
[markup.goldmark.renderer]
    unsafe = true
    hardWraps = true