modalbuttontext =  "Get a Quote"
company     =   '#company'
company2    =   '#companyTagline'
fullname    =   '#companyFullName'
slogan      =   '#slogan '
industry    =   '#industry'
years       =   '#years'
street      =   '#street'
towncity    =   '#towncity'
county      =   '#county'
postcode    =   '#postcode' 
phone       =   '#phone'
mobile      =   '#mobile'
email       =   '#email'
facebook    =   '#fb'
instagram   =   '#ig'
twitter     =   '#tw'
tiktok      =   '#tok'
checkatrade =   '#'
ratedpeople =   '#'
yell        =   '#'
bookabuilder    =   '#'