modalbuttontext =  "Get a Quote"
company     =   "Osprey Roofing"
fullname    =   "Osprey Roofing"
slogan      =   ""
logo		=	"logo.png"
emblem		=	""
industry    =   "roofing"
years       =   "15 years"
building    =   ""
street      =   "23 Kinsbourne Way"
towncity    =   "Southampton"
county      =   "Hampshire"
postcode    =   "SO19 6HB" 
phone       =   ""
mobile      =   "07809 740 119"
email       =   "info@ospreyroofing.uk"
facebook    =   ""
instagram   =   ""
twitter     =   ""
tiktok      =   ""
checkatrade =   "ospreyroofing"
ratedpeople =   ""
yell        =   "osprey-roofing-southampton-10235220/"
bookabuilder=   ""
mybuilder 	=	""
localheroes	=	""
watersafe   =   ""
