modalbuttontext =  "Get a Quote"
company     =   "Sky Craft Property Improvements"
company2    =   "Roofing experts"
fullname    =   "Sky Craft Property Improvements"
slogan      =   "#companySlogan"
industry    =   "roofing"
years       =   "#years"
street      =   "Unit B, 57 Park Road"
towncity    =   "London"
county      =   "South East"
postcode    =   "N8 8SY" 
phone       =   "02087 724 861"
mobile      =   "07542 170 523 "
email       =   "07542170523"
facebook    =   ""
instagram   =   ""
twitter     =   ""
tiktok      =   ""
checkatrade =   ""
ratedpeople =   ""
yell        =   ""
bookabuilder=   ""
