modalbuttontext =  "Get a Quote"
company     =   "Fresh Big Licks"
fullname    =   "Fresh Big Licks Interior Decorators"
slogan      =   "#companySlogan"
logo		=	"logo.png"
industry    =   "painting and decorating"
emblem		=	"gsr-logo.png"
years       =   "#years"
street      =   "20 Kenilworth Way"
towncity    =   "Paisley"
county      =   "Renfrewshire"
postcode    =   "PA2 0LL" 
phone       =   ""
mobile      =   "07498 646 236"
email       =   "carolineclements32@gmail.com"
facebook    =   "freshbiglicks"
instagram   =   ""
twitter     =   ""
tiktok      =   ""
checkatrade =   "freshbiglicksinteriordecorators"
ratedpeople =   ""
yell        =   "fresh-big-licks-interior-decorators-paisley-9285615"
bookabuilder=   ""
mybuilder 	=	""