modalbuttontext =  "Get a Quote"
company     =   "Plumbfixer Ltd"
fullname    =   "Plumbfixer Ltd"
slogan      =   ""
logo		=	"logo.png"
emblem		=	""
industry    =   "plumbing"
seo         =   "plumber"
years       =   "many years"
building    =   ""
street      =   "10 Salvia Close"
towncity    =   "Cardiff"
county      =   "South Glamorgan"
postcode    =   "CF3 0JF" 
phone       =   "07453 545 787"
mobile      =   ""
email       =   "plumbfixerltd@mail.com"
facebook    =   ""
instagram   =   ""
twitter     =   ""
tiktok      =   ""
checkatrade =   ""
ratedpeople =   "plumfixer"
yell        =   "plumbfixer-ltd-cardiff-10711278"
bookabuilder=   ""
mybuilder 	=	""
localheroes	=	""
watersafe   =   ""
tradesmen   =   ""
trustatrader=   ""
