modalbuttontext =  "Get a Quote"
company     =   "SF Plumbing & Tiling"
fullname    =   "SF Plumbing & Tiling"
slogan      =   "Local, Reliable, Professional"
logo		=	"logo.png"
industry    =   "plumbing and tiling"
years       =   "#years"
street      =   "1 Stork Close"
towncity    =   "Blackpool"
county      =   "Lancashire"
postcode    =   "FY5 3FB" 
phone       =   ""
mobile      =   "07706 305 148"
email       =   "info@sfplumbingandtiling.co.uk"
facebook    =   "people/SF-Plumbing-Tiling/100085091921666"
instagram   =   "sf_plumbingandtiling"
twitter     =   "#"
tiktok      =   "#"
checkatrade =   "#"
ratedpeople =   "#"
yell        =   "sf-plumbing-and-tiling-thornton-cleveleys-10494757"
bookabuilder=   "#"
mybuilder 	=	"#"