modalbuttontext =  "Get a Quote"
company     =   "#companyName"
company2    =   "#jobDescription"
fullname    =   "#companyFullName"
slogan      =   "#companySlogan"
industry    =   "#industry"
years       =   "#years"
street      =   "#street"
towncity    =   "#towncity"
county      =   "#county"
postcode    =   "#postcode" 
phone       =   "#phone"
mobile      =   "#mobile"
email       =   "#email"
facebook    =   "#social"
instagram   =   "#social"
twitter     =   "#social"
tiktok      =   "#social"
checkatrade =   "#social"
ratedpeople =   "#social"
yell        =   "#social"
bookabuilder=   "#social"
mybuilder 	=	"#social"