modalbuttontext =  "Get a Quote"
company     =   "Advanced Tree Company"
fullname    =   "Advanced Tree Company"
slogan      =   ""
logo		=	""
emblem		=	""
industry    =   "tree care and landscaping"
years       =   "15 years"
building    =   ""
street      =   "41 Broom Field"
towncity    =   "Surrey"
county      =   "Hampshire"
postcode    =   "GU18 5QN" 
phone       =   "07437 695 761"
mobile      =   ""
email       =   "landscapesuk@outlook.com"
facebook    =   ""
instagram   =   ""
twitter     =   ""
tiktok      =   ""
checkatrade =   ""
ratedpeople =   ""
yell        =   ""
bookabuilder=   ""
mybuilder 	=	""
localheroes	=	""
watersafe   =   ""
tradesmen   =   ""
trustatrader=   ""
