
modalbuttontext =  "Get a Quote"
company     =   "You've Been Recovered"
company2    =   "24/7 Nationwide Roadside Assistance"
fullname    =   "You've Been Recovered 24/7"
slogan      =   "24/7 Roadside assistance"
industry    =   "vehicle recovery"
years       =   "#years"
street      =   "38 Waukglen Drive"
towncity    =   "Glasgow"
county      =   "Scotland"
postcode    =   "G53 7UG" 
phone       =   ""
mobile      =   "07763 732 212"
email       =   "faizMuhammed868@gmail.com"
facebook    =   ""
instagram   =   ""
twitter     =   ""
tiktok      =   ""
checkatrade =   ""
ratedpeople =   ""
yell        =   ""
bookabuilder=   ""