modalbuttontext =  "Get a Quote"
company     =   "Climate Eco Heating"
fullname    =   "Climate Eco Heating"
slogan      =   ""
logo		=	"logo.png"
emblem		=	"creds/gas-safe-trans.png"
industry    =   "gas and heating"
seo         =   "gas engineer"
years       =   "23+ years"
building    =   ""
street      =   "59 Tide Way"
towncity    =   "Chichester"
county      =   "West Sussex"
postcode    =   "PO20 8FE" 
phone       =   "07540 314 595"
mobile      =   ""
email       =   "climateecoheating@gmail.com"
facebook    =   ""
instagram   =   ""
twitter     =   ""
tiktok      =   ""
checkatrade =   "climateecoheating"
ratedpeople =   ""
yell        =   ""
bookabuilder=   ""
mybuilder 	=	""
localheroes	=	""
watersafe   =   ""
tradesmen   =   ""
trustatrader=   ""
