modalbuttontext =  "Get a Quote"
company     =   "#companyName"
fullname    =   "#companyFullName"
slogan      =   ""
logo		=	""
emblem		=	"creds/gas-safe.png"
industry    =   "#industry"
years       =   "#years"
building    =   ""
street      =   "#street"
towncity    =   "#towncity"
county      =   "#county"
postcode    =   "#postcode" 
phone       =   "#phone"
mobile      =   "#mobile"
email       =   "#email"
facebook    =   "#s"
instagram   =   ""
twitter     =   ""
tiktok      =   ""
checkatrade =   ""
ratedpeople =   ""
yell        =   ""
bookabuilder=   ""
mybuilder 	=	""
localheroes	=	""
watersafe   =   ""
tradesmen   =   ""
