modalbuttontext =  "Get a Quote"
company     =   "#companyName"
company2    =   "#jobDescription"
fullname    =   "#companyFullName"
slogan      =   "#companySlogan"
industry    =   "#industry"
years       =   "#years"
street      =   "#street"
towncity    =   "#towncity"
county      =   "#county"
postcode    =   "#postcode" 
phone       =   "#phone"
mobile      =   "#mobile"
email       =   "#email"
facebook    =   "#s"
instagram   =   "#s"
twitter     =   "#s"
tiktok      =   "#s"
checkatrade =   "#s"
ratedpeople =   "#s"
yell        =   "#s"
bookabuilder=   "#s"
mybuilder 	=	"#s"