modalbuttontext =  "Get a Quote"
company     =   "Umbrella Plumbing"
fullname    =   "Umbrella Plumbing Services"
logo 		=	"logo-wide.jpg"
slogan      =   "#companySlogan"
industry    =   "plumbing"
years       =   "#years"
street      =   "275"
towncity    =   "Hull"
county      =   "East Yorkshire"
postcode    =   "HU4 7RY" 
phone       =   ""
mobile      =   "#mobile"
email       =   "umbrellaplumbinghull@gmail.com"
facebook    =   "#"
instagram   =   "#"
twitter     =   "#"
tiktok      =   "#"
checkatrade =   "#"
ratedpeople =   "#"
yell        =   "umbrella-plumbing-services-hull-10460349"
bookabuilder=   "#"
mybuilder 	=	"#"